# Generated by Django 4.1.3 on 2023-01-19 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketCinema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticketNumber', models.IntegerField()),
                ('sessionNumber', models.IntegerField()),
                ('placeNumber', models.IntegerField()),
                ('servation', models.IntegerField()),
            ],
        ),
    ]
