# Generated by Django 4.1.3 on 2023-01-28 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_ticketcinema'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('familia', models.CharField(max_length=20)),
                ('otchestvo', models.CharField(max_length=20)),
                ('login', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('mail', models.CharField(max_length=20)),
                ('number', models.CharField(max_length=20)),
                ('birthday', models.CharField(max_length=20)),
            ],
        ),
    ]
