# Generated by Django 4.1.3 on 2023-02-27 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0004_hall_movie_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
