# Generated by Django 4.1.3 on 2023-03-05 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0005_alter_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='hall',
            name='scheme',
            field=models.CharField(default=0, max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hall',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
