# Generated by Django 4.1.3 on 2023-03-11 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0006_hall_scheme_alter_hall_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
